from django.contrib.auth.views import LoginView
from django.urls import path

from catalog.views import (
    IndexView,
    TopicListView,
    NewspaperListView,
    RedactorListView,
    NewspaperDetailView,
    RedactorDetailView,
    LogoutConfirmView,
    NewspaperCreateView,
    TopicCreateView,
    RedactorCreateView,
    NewspaperUpdateView,
    RedactorUpdateView,
    TopicUpdateView,
    NewspaperDeleteView,
    RedactorDeleteView,
    TopicDeleteView,
    TopicDetailView,
    NewspaperToggleAssignView,
)

urlpatterns = [
    path(
        "", IndexView.as_view(),
        name="index"
    ),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list",
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "topics/<int:pk>/",
        TopicDetailView.as_view(),
        name="topic-detail",
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
    "newspapers/<int:pk>/toggle-assign/",
        NewspaperToggleAssignView.as_view(),
        name="toggle-newspaper-assign",
    ),
    path(
        "confirm-logout/",
        LogoutConfirmView.as_view(),
        name="logout-confirm-view"
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login"
    )
]


app_name = "catalog"
